[package]
name = "classparse"
version = "0.1.0"
authors = ["Kartikaya Gupta"]
edition = "2018"
license = "0BSD"

description = "A simple parser for Java class files"
homepage = "https://github.com/staktrace/classparse/blob/master/README.md"
repository = "https://github.com/staktrace/classparse"
readme = "README.md"
keywords = ["parser", "java", "class", "jvm"]
categories = ["parsing"]

[badges]
travis-ci = { repository = "staktrace/classparse" }
maintenance = { status = "passively-maintained" }

[dependencies]
cesu8 = "1.1.0"
